spring.application.name=libraryapp
# URI de conexion a tu cluster de MongoDB Atlas
# Reemplaza <username>, <password> y <cluster-url> por los datos reales de tu cluster
#spring.data.mongodb.uri=mongodb+srv://<admin>:<admin123>@librarydb.tsinh8j.mongodb.net/?appName=librarydb
spring.data.mongodb.uri=mongodb+srv://admin:admin123@librarydb.tsinh8j.mongodb.net/librarydb?retryWrites=true&w=majority&appName=librarydb